### ISSUE TITLE
config_template.py requirement

### ISSUE THREAD

**Issue by bjne** [ceph/ansible-ceph-common#4]
Hi, Sébastien

When using galaxy to pull ansible-ceph components, and when it comes to at least
ceph-common it is missing the config_template.py action plugin.

I have solved this locally by placing config_template.py in roles_path/ceph-common/library

Can you please do this upstream? I can eventually do a pull request...

Also, have you tought of having all the ansible-ceph-* modules only in separate repos
and pull everything into ansible-ceph using galaxy and requirements.yml? I would find
that a bit cleaner..

**Comment by leseb** [comment]
Hey @bjne,

Thanks for reporting this issue.
I won't mind having a PR :).

Yes I believe the discussion of pulling the galaxy from ceph-ansible started here: https://github.com/ceph/ceph-ansible/issues/388 and tried to addressed this in https://github.com/ceph/ceph-ansible/pull/404

But I recently found out about the `requirements.yml` thing. I'll see if I can have a look at that.
Ideally if you want to propose something I won't say no :), I'm kinda overloaded at the moment.

**Comment by leseb** [comment]
@bjne just moved `plugins/actions/config_template.py` to ansible-ceph-common.

**Comment by bjne** [comment]
I was perhaps a bit quick in saying that this will work (putting
config_template.py
in library)..

Looks like ansible does not currently support action plugins in roles, but
there is
a somehow ugly workaround I managed to get working:

1) place a config_template.py in library with only a shebang and perhaps
some
DOCUMENTATION = ''' ...

2) place the real config_template.py in action_plugins inside role

3) have ansible.cfg in main repo point action_plugins to
..../ceph-common/action_plugins

..do not understand why this is needed or if it is possible to get past in
some way,
will look more into it, but lots of information here..

-- 
Bj(/)rnar

**Comment by leseb** [comment]
Ok I see, I added a reference in the README anyway. Thanks for the explanations above :)
