### ISSUE TITLE
mds/cephfs in common?

### ISSUE THREAD

**Issue by bjne** [ceph/ansible-ceph-common#5]
Is really ceph-mds a requirement of the common role?

**Comment by leseb** [comment]
@bjne yes it is, why this question? ceph-common is needed to mainly install ceph and generates the `ceph.conf`.

**Comment by bjne** [comment]
Mainly because mds package is broken in xenial
Also, I am not using cephfs, so dont understand all the mds/cephfs deps in
the common role. Perhaps it could be moved or made optional?

**Comment by leseb** [comment]
you're right I shouldn't be installing ceph-mds by default. I'll fix that.

**Comment by leseb** [comment]
can you open a request on ceph-ansible instead? easier to track
